version: '3'

services:
    web:
        build:
            context: .
            dockerfile: docker/nginx/Dockerfile
        container_name: vinchecker-web
        ports:
            - "8080:80"
        volumes:
            - .:/app/
        links:
            - php

    php:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        container_name: vinchecker-php
        environment:
            - DATABASE_USERNAME=vinchecker
            - DATABASE_PASSWORD=aifae4UH>aiquie
            - DATABASE_HOST=db
            - DATABASE_NAME=vinchecker
            - DATABASE_PORT=5435
        volumes:
            - .:/app/
        links:
            - db

    db:
        image: 'postgres:latest'
        container_name: vinchecker-db
        ports:
            - "5435:5432"
        environment:
            - POSTGRES_USER=vinchecker
            - POSTGRES_PASSWORD=aifae4UH>aiquie
            - POSTGRES_DB=vinchecker
        volumes:
            - /var/local/vinchecker:/var/lib/postgresql/data
        command: -p 5435
